using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.IO;
using Microsoft.Office.Interop.Word;

namespace codefunwordgen
{
    class Program
    {
        static void Main(string[] args)
        {
            Application WordApp = new Application();
            Document WordDoc = new Document();

            WordApp.Visible = false;
            WordDoc         = WordApp.Documents.Add();

            WordApp.Selection.TypeText("CODEFUN ANSWERSHEET\n");
            WordApp.Selection.TypeText("Generated by bentokun's codefun generator\n\n");

            object WordFileName = @"codefungen.docx";
            int i = 0;

            while (i<args.Count() - 1)
            {
                if (args[i] == "-s")
                {
                    WordFileName = args[++i];
                }

                i++;
            }
               
            using (StreamReader sr = File.OpenText(args[args.Count() - 1])){
                string Line, FileName = "";
                string PreviousLine = "";

                while ((Line = sr.ReadLine()) != null)
                {
                    if (Line == "")
                    {
                        Line = PreviousLine;
                    }
                    else
                    {
                        if ((Line.Contains("```")) && (Line.Length > 3))
                        {
                            FileName = PreviousLine;

                            while ((FileName[0] == ' ') || (FileName[0] == '#'))
                            {
                                FileName=FileName.Remove(0, 1);
                            }

                            WordApp.Selection.TypeText(FileName + "\n");

                            while ((Line=sr.ReadLine()) != "```")
                            {
                                WordApp.Selection.TypeText(Line + "\n");
                            }
                            
                            WordApp.Selection.TypeText("\n");
                        }

                        PreviousLine = Line;
                
                    }
                }
            }

            WordDoc.SaveAs(ref WordFileName);
        }
    }
}
